package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runGenPages writes src/dashboard/data/pages.js from the Go data above.
// The output is human-readable so a `git diff` after editing pages.go is easy
// to read.
func runGenPages(_ []string) error {
	target := filepath.Join("src", "dashboard", "data", "pages.js")
	data := emitPagesJS()
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(data), 0o644); err != nil {
		return err
	}
	fmt.Printf("✓ wrote %s (%d bytes)\n", target, len(data))
	return nil
}

func emitPagesJS() string {
	var sb strings.Builder

	// Header.
	sb.WriteString("// Generated by `dashctl gen-pages` from api/cmd/dashctl/pages.go.\n")
	sb.WriteString("// Do NOT edit by hand — your changes will be overwritten on the next regen.\n\n")

	// sidebarLinks
	sb.WriteString("export const sidebarLinks = [\n")
	for _, s := range sections {
		sb.WriteString("  ")
		sb.WriteString(linkLiteral(s.Sidebar))
		sb.WriteString(",\n")
	}
	sb.WriteString("];\n\n")

	// Per-section right-nav arrays
	for _, s := range sections {
		if s.JSVar == "" || len(s.RightNav) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "const %s = [\n", s.JSVar)
		for _, n := range s.RightNav {
			sb.WriteString("  ")
			sb.WriteString(rightNavLiteral(n))
			sb.WriteString(",\n")
		}
		sb.WriteString("];\n\n")
	}

	// getRoute helper — verbatim port of the original.
	sb.WriteString(`export function getRoute(hash) {
  const value = hash.startsWith('#/') ? hash.slice(2) : hash.startsWith('#') ? hash.slice(1) : hash;
  return value || 'dashboard';
}

`)

	// routes map
	sb.WriteString("export const routes = {\n")

	// Root routes first (e.g. "dashboard").
	for _, r := range rootRoutes {
		writeRoute(&sb, r, "")
	}

	// Then each section's routes.
	for _, s := range sections {
		for _, r := range s.Routes {
			active := r.SidebarActive
			if active == "" {
				active = s.Sidebar.ID
			}
			writeRoute(&sb, RouteEntry{
				Path:          r.Path,
				Component:     r.Component,
				PageTitle:     r.PageTitle,
				SidebarActive: active,
			}, s.JSVar)
		}
	}

	sb.WriteString("};\n")
	return sb.String()
}

// writeRoute emits one entry of the routes map. rightNavVar may be the empty
// string for routes without a right-rail.
func writeRoute(sb *strings.Builder, r RouteEntry, rightNavVar string) {
	key := jsKey(r.Path)
	rn := "[]"
	if rightNavVar != "" {
		rn = rightNavVar
	}
	fmt.Fprintf(sb, "  %s: {\n", key)
	fmt.Fprintf(sb, "    componentName: %s,\n", jsString(r.Component))
	fmt.Fprintf(sb, "    pageTitle: %s,\n", jsString(r.PageTitle))
	fmt.Fprintf(sb, "    sidebarActive: %s,\n", jsString(r.SidebarActive))
	fmt.Fprintf(sb, "    contentHtml: '',\n")
	fmt.Fprintf(sb, "    rightNav: %s,\n", rn)
	sb.WriteString("  },\n")
}

// linkLiteral returns the inline JS object for a sidebar link.
func linkLiteral(l SidebarLink) string {
	return fmt.Sprintf("{ path: %s, icon: %s, label: %s, id: %s }",
		jsString(l.Path), jsString(l.Icon), jsString(l.Label), jsString(l.ID))
}

func rightNavLiteral(n RightNavItem) string {
	return fmt.Sprintf("{ path: %s, icon: %s, label: %s, id: %s }",
		jsString(n.Path), jsString(n.Icon), jsString(n.Label), jsString(n.ID))
}

// jsString single-quotes a string for JS source. Falls back to JSON encoding
// for anything containing a single quote so we never emit broken syntax.
func jsString(s string) string {
	if !strings.ContainsAny(s, `'\`) {
		return "'" + s + "'"
	}
	b, _ := json.Marshal(s)
	return string(b)
}

// jsKey emits a property key — bare when it's a simple identifier, quoted
// otherwise. Routes like "tickets/tickets" must be quoted.
func jsKey(s string) string {
	if isIdent(s) {
		return s
	}
	return jsString(s)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if !(r == '_' || r == '$' ||
			(r >= 'a' && r <= 'z') ||
			(r >= 'A' && r <= 'Z') ||
			(i > 0 && r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}
